apiVersion: cluster.open-cluster-management.io/v1beta1
kind: BackupSchedule
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: schedule-acm
  namespace: open-cluster-management-backup
spec:
  veleroSchedule: "0 */6 * * *"
  veleroTtl: 720h
  useManagedServiceAccount: true
