apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - multiclusterhub-patch.yaml
  - credentials-secret.yaml
  - dataprotectionapplication.yaml
  - backupschedule.yaml
  # Uncomment only when restoring to a new hub cluster:
  # - restore.yaml
