apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fileintegrity-worker.yaml
  - fileintegrity-master.yaml
  # Uncomment for custom AIDE configuration:
  # - aide-config.yaml
  # - fileintegrity-worker-custom.yaml
