apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-app-db-creds
  namespace: demo-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: demo-app-db-creds
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: /demo-app/prod/db
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /demo-app/prod/db
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: /demo-app/prod/db
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: /demo-app/prod/db
        property: port
    - secretKey: DB_NAME
      remoteRef:
        key: /demo-app/prod/db
        property: dbname
