apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-compliance-manager
rules:
  - apiGroups:
      - compliance.openshift.io
    resources:
      - scansettings
      - scansettingbindings
      - tailoredprofiles
      - compliancescans
      - compliancesuites
      - complianceremediations
      - compliancecheckresults
      - profiles
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
