apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management-backup
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    # Required: cluster-backup only watches this namespace.
    openshift.io/cluster-monitoring: "true"
