apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-acm-oadp-backup-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
rules:
  - apiGroups:
      - external-secrets.io
    resources:
      - externalsecrets
      - secretstores
      - clustersecretstores
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - oadp.openshift.io
    resources:
      - dataprotectionapplications
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - backupschedules
      - restores
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
