apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: dpa-acm
  namespace: open-cluster-management-backup
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  configuration:
    velero:
      defaultPlugins:
        - openshift
        - aws
    nodeAgent:
      enable: false
      uploaderType: kopia
  backupImages: false
  backupLocations:
    - velero:
        provider: aws
        default: true
        objectStorage:
          bucket: ravi-rosa-hub-hcp-acm-backup
          prefix: acm-backup
        config:
          region: us-east-2
          s3ForcePathStyle: "false"
          profile: default
        credential:
          name: cloud-credentials
          key: credentials
