apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloud-credentials
  namespace: open-cluster-management-backup
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: cloud-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        credentials: |
          [default]
          role_arn = {{ .role_arn }}
          web_identity_token_file = /var/run/secrets/openshift/serviceaccount/token
  data:
    - secretKey: role_arn
      remoteRef:
        key: oadp/acm-backup-credentials
        property: role_arn
