apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: dpa-acm
  namespace: open-cluster-management-backup
spec:
  configuration:
    velero:
      defaultPlugins:
        - openshift
        - aws
    nodeAgent:
      enable: false
  backupImages: false
  features:
    dataMover:
      enable: false
  backupLocations:
    - velero:
        provider: aws
        default: true
        objectStorage:
          bucket: <YOUR_S3_BUCKET>
          prefix: acm-backup
        config:
          region: <YOUR_AWS_REGION>
          s3ForcePathStyle: "false"
          profile: default
        credential:
          name: cloud-credentials
          key: credentials
