apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-acm-oadp-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups:
      - oadp.openshift.io
    resources:
      - dataprotectionapplications
      - cloudstorages
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - backupschedules
      - restores
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - velero.io
    resources:
      - backups
      - restores
      - schedules
      - backupstoragelocations
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - external-secrets.io
    resources:
      - externalsecrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
