apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  # clusterrole and clusterrolebinding are applied by Terraform
  # to avoid chicken-and-egg with ArgoCD permissions
