apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - scansetting.yaml
  - scansettingbinding-cis.yaml
  - scansettingbinding-moderate.yaml
  # Uncomment the profiles you need:
  # - scansettingbinding-pci-dss.yaml
  # - tailoredprofile-cis-custom.yaml
