apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Non-STS AWS with long-lived keys in Secrets Manager. Not for ROSA HCP.
patches:
  - path: externalsecret-static-keys.yaml
  - target:
      group: oadp.openshift.io
      version: v1alpha1
      kind: DataProtectionApplication
      name: dpa-acm
    patch: |-
      - op: replace
        path: /spec/backupLocations/0/velero/objectStorage/bucket
        value: REPLACE_ME_BUCKET
      - op: replace
        path: /spec/backupLocations/0/velero/config/region
        value: us-east-1
